#for local
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     env_file:
#       - ./backend/.env.prod # Load all variables from this file
#     ports:
#       - "3001:3001" # The host port should match the PORT in your .env file if possible

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000" # The host port should match the PORT in your .env file if possible
#     depends_on:
#       - backend

# for github
services:
  mongo:
    image: "mongo"
    ports:
      - "8080:27017"
    volumes:
      - ./mongo_data:/data/db

  backend:
    build: "./backend"
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - "./backend/.env.prod"

  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - "./frontend/.env.prod"
